server:
  port: ${myapp.port:8989}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#JAP SQL의 바인딩된 파라미터가 보이게 설정함.
logging:
  level:
    #"[org.springframework]": ERROR
    #"[org.hibernamte]": ERROR
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    
    #"[com.jhcode33.jwt.JsonWebTokenApplication]": ERROR
    

spring:
  datasource:
    #mariadb는 자신이 사용하고자 하는 스키마를 입력해야지 들어가짐.
    url: jdbc:mariadb://localhost:3306/jwt
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa: 
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA가 사용할 database의 dialect 설정
    properties:
      hibernate:
        hibernate:
        "[show_sql]" : true
        "[format_sql]": true            #SQL을 보기 좋게 출력
        "[user_sql_comments]": true     #SQL생성 시 주석 포함
        "[highlight_sql]": true         #SQL에 색깔
        "[hbm2ddl.auto]": update
    open-in-view: false